- name: zaxh tasks for test3
  hosts: localhost
  connection: local
  tasks:
    - name: Compile produce  using Maven
      shell: |
        cd /Users/huguiqi/Public/javaWorkspace/zaxh/frp_project/za/za-service/service-produce 
        mvn clean package -DskipTests
      register: maven_output
      tags:
      - produce

    - name: Compile frpza using Maven
      shell: |
        cd /Users/huguiqi/Public/javaWorkspace/zaxh/frp_project/za
        git pull origin shanghai-hotfix100 -f
        mvnd clean package -DskipTests -Dquickly
      register: maven_output
      tags:
      - za

    - name: Compile produce-server  using Maven
      shell: |
        cd /Users/huguiqi/Public/javaWorkspace/zaxh/frp_project/za/za-service/service-produce/service-produce-server
        mvn clean package -DskipTests
      register: maven_output
      tags:
      - produce-server

    - name: Display Maven output
      debug:
        var: maven_output.stdout_lines
      tags:
      - produce
      - produce-server
      - za

- hosts: test3
  remote_user: root
  tasks:
   - name: check server pid
     shell: ps -ef | grep 'service-produce-server' | grep 'java' | grep -v grep | awk '{print $2}'
     ignore_errors: True
     register: server_output
     tags:
     - check

   - name: kill pid
     shell: kill -9 {{result_pid.stdout}}
     when: result_pid.stdout|int > 0
     tags:
     - kill
   - name: stop server
     shell: cd /var/gameplat/snkoudai/service-produce-server && ./app.sh stop
     tags:
     - stop
     
   - name: restart server
     shell: |
      cd /var/gameplat/snkoudai/service-produce-server 
      app.sh restart
     register: server_output
     tags:
     - restart
   
   - name: start server
     shell: cd /var/gameplat/snkoudai/service-produce-server && sh ./app.sh start
     register: server_output
     tags:
     - start


   - name: Display server output
     debug:
        var: server_output.stdout_lines
     tags: 
        - restart
        - stop
        - start
        - upload
        - deploy
        - check

   - name: stop produce-server for deploy
     shell: | 
         cd /var/gameplat/snkoudai/service-produce-server
         sh ./app.sh stop
     register: server_output
     tags:
     - deploy

   - name: Pause before backup
     pause:
        seconds: 5      # 延迟 5 秒
     tags: deploy     

   - name: backup old JAR file for produce-server
     shell: | 
       cd /var/gameplat/snkoudai/service-produce-server
       sh ./app.sh backup
     register: server_output
     tags: deploy
  
   - name: Delete existing JAR file for produce-server
     file:
      path: /var/gameplat/snkoudai/service-produce-server/service-produce-server.jar
      state: absent
     tags: deploy

   - name: Pause before upload
     pause:
        seconds: 5      # 延迟 5 秒
     tags: deploy

   - name: Upload JAR file to remote server
     copy:
      src: /Users/huguiqi/Public/javaWorkspace/zaxh/frp_project/za/za-service/service-produce/service-produce-server/target/service-produce-server.jar
      dest: /var/gameplat/snkoudai/service-produce-server/service-produce-server.jar
      force: yes  # 强制覆盖
      owner: root
      group: app_group
      mode: '0644'
     ignore_errors: yes  # 忽略错误         
     tags:
       - deploy

   - name: Pause before starting server
     pause:
        seconds: 5   # 延迟 10 秒
     tags: deploy

   - name: start server for deploy
     shell: | 
       cd /var/gameplat/snkoudai/service-produce-server 
       sh ./app.sh start
     register: server_output
     tags:
     - deploy