- name: snbt tasks for test1
  hosts: test1
  remote_user: root
  tasks:
   - name: check server pid
     shell: ps -ef | grep 'tongweb' | grep '/bin/java' | grep -v grep | awk '{print $2}'
     ignore_errors: True
     register: result_pid
     tags:
     - stop
   - name: kill pid
     shell: kill -9 {{result_pid.stdout}}
     when: result_pid.stdout|int > 0
     tags:
     - stop
   - name: restart server
     shell: cd /data/Seeyon/TongWeb7/bin/ && ./restart.sh
     tags:
     - restart

   - name: clean data backup
     cron: 
        name: playbook for clean /data/backup
        day: /2
        job: /bin/bash -x /data/Seeyon/shell/clean.sh
        state: present
     tags:
     - jop
